sonar.projectKey=nvb33_LibraryOfThings
sonar.organization=nvb33
sonar.projectName=Library of Things
sonar.projectVersion=1.0

sonar.sources=StarterApp,StarterApp.Database
sonar.tests=StarterApp.Tests

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/obj/**,**/bin/**,**/Migrations/**,**/*.xaml
sonar.test.exclusions=StarterApp.Tests/**
