name: Documentation

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Doxyfile
        run: doxygen -g

      - name: Generate Doxygen Documentation
        run: doxygen .

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: html